name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        arch: [arm64, x64]
        exclude:
        - os: windows-latest
          arch: arm64
      fail-fast: false
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with: 
          submodules: recursive

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.1'

      - name: Build project
        run: |
          cd ./gpressdatadir && unzip dict.zip && rm -rf ./dict.zip && cd ..

          if [ "${{ matrix.os }}" == "macos-latest" ]; then
            if [ "${{ matrix.arch }}" == "arm64" ]; then
              mv ./gpressdatadir/fts5/libsimple.dylib ./gpressdatadir/fts5/temp.dylib
              GOOS=darwin GOARCH=arm64 go build --tags "fts5" -ldflags "-w -s"
            else
              mv ./gpressdatadir/fts5/libsimple.dylib-amd64 ./gpressdatadir/fts5/temp.dylib
              GOOS=darwin GOARCH=amd64 go build --tags "fts5" -ldflags "-w -s"
            fi
            rm -rf ./gpressdatadir/fts5/libsimple*
            mv ./gpressdatadir/fts5/temp.dylib ./gpressdatadir/fts5/libsimple.dylib
          fi   

          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            if [ "${{ matrix.arch }}" == "arm64" ]; then
              mv ./gpressdatadir/fts5/libsimple.so-aarch64 ./gpressdatadir/fts5/temp.so
              GOOS=linux GOARCH=arm64 go build --tags "fts5" -ldflags "-w -s"
            else
              mv ./gpressdatadir/fts5/libsimple.so ./gpressdatadir/fts5/temp.so
              go build --tags "fts5" -ldflags "-w -s"
            fi
            rm -rf ./gpressdatadir/fts5/libsimple*
            mv ./gpressdatadir/fts5/temp.so ./gpressdatadir/fts5/libsimple.so
          fi

          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            mv ./gpressdatadir/fts5/libsimple.dll ./gpressdatadir/fts5/temp.dll
            rm -rf ./gpressdatadir/fts5/libsimple*
            mv ./gpressdatadir/fts5/temp.dll ./gpressdatadir/fts5/libsimple.dll
            
            go build --tags "fts5" -ldflags "-w -s"
          fi

          mkdir -p ./temp/gpress && mv ./gpress ./temp/gpress/ 
          mv ./gpressdatadir ./temp/gpress/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gpress-${{ matrix.os }}-${{ matrix.arch }}
          path: ${{ github.workspace }}/temp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}