name: release
### 手动触发,目前Linux glibc版本不兼容,需要手动编译.两层压缩包
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.1'

      - name: CreateDir
        run: |
          mkdir -p ./temp/gpress/     

      - name: Build
        uses: goreleaser/goreleaser-action@v5
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: latest
          workdir: ./temp/gpress/
          args: release --clean --tags "fts5" -ldflags "-w -s"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   